[package]
name = "guesser"
version = "0.1.0"
edition = "2021"
repository = "https://www.github.com/chrischtel/guesser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
rand = "0.8.5"
